version: '3.8'

services:
  # Aplicación Flask con SQLite
  web:
    build: .
    container_name: gestion-documental-web
    ports:
      - "127.0.0.1:8080:8080"  # Solo accesible desde localhost
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///app/gestion_documental.db
      - SECRET_KEY=gestion_documental_secret_key_2024_very_secure_change_in_production
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - EMAIL_SENDER=estadisticatessa@gmail.com
      - EMAIL_PASSWORD=rxcd epqr gebp myhj
      - UPLOAD_FOLDER=static/uploads
      - MAX_FILE_SIZE=16777216
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./instance:/app/instance
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: gestion-documental-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

